<?php
// $nametype = "dich-vu";
// $config['news'][$nametype]['title_main'] = "Dịch vụ";
// $config['news'][$nametype]['dropdown'] = true;
// $config['news'][$nametype]['list'] = true;
// $config['news'][$nametype]['tags'] = [];
// $config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = true;
// $config['news'][$nametype]['slug'] = true;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['images'] = true;
// $config['news'][$nametype]['show_images'] = true;
// $config['news'][$nametype]['gallery'] = array();
// $config['news'][$nametype]['desc'] = true;
// $config['news'][$nametype]['content'] = true;
// $config['news'][$nametype]['content_cke'] = true;
// $config['news'][$nametype]['seo'] = true;
// $config['news'][$nametype]['schema'] = true;
// $config['news'][$nametype]['width'] = 560;
// $config['news'][$nametype]['height'] = 315;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['icon'] = false;
// $config['news'][$nametype]['width_icon'] = 200;
// $config['news'][$nametype]['height_icon'] = 130;
// $config['news'][$nametype]['thumb_icon'] = '100x65x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

// /* (List) */
// $config['news'][$nametype]['title_main_list'] = "Danh mục cấp 1";
// $config['news'][$nametype]['images_list'] = true;
// $config['news'][$nametype]['show_images_list'] = true;
// $config['news'][$nametype]['slug_list'] = true;
// $config['news'][$nametype]['check_list'] = array("noibat" => "Nổi bật", "hienthi" => "Hiển thị");
// $config['news'][$nametype]['gallery_list'] = array();
// $config['news'][$nametype]['desc_list'] = false;
// $config['news'][$nametype]['desc_cke_list'] = false;
// $config['news'][$nametype]['content_list'] = true;
// $config['news'][$nametype]['content_cke_list'] = true;
// $config['news'][$nametype]['seo_list'] = true;
// $config['news'][$nametype]['width_list'] = 500;
// $config['news'][$nametype]['height_list'] = 500;
// $config['news'][$nametype]['thumb_list'] = '100x100x1';
// $config['news'][$nametype]['icon_list'] = false;
// $config['news'][$nametype]['width_icon_list'] = 200;
// $config['news'][$nametype]['height_icon_list'] = 130;
// $config['news'][$nametype]['thumb_icon_list'] = '100x65x1';
// $config['news'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Catalogue */
$nametype = "catalogue";
$config['news'][$nametype]['title_main'] = "Catalogue";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';
$config['news'][$nametype]['file'] = true;
$config['news'][$nametype]['file_type'] = '.doc|.docx|.pdf|.rar|.zip|.ppt|.pptx|.xls|.xlsx';

/* Tài liệu kỹ thuật */
$nametype = "tai-lieu-ky-thuat";
$config['news'][$nametype]['title_main'] = "Tài liệu kỹ thuật";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';
$config['news'][$nametype]['file'] = true;
$config['news'][$nametype]['file_type'] = '.doc|.docx|.pdf|.rar|.zip|.ppt|.pptx|.xls|.xlsx';



/* Tin tức */
$nametype = "tin-tuc";
$config['news'][$nametype]['title_main'] = "Tin tức";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';
$config['news'][$nametype]['file'] = false;
$config['news'][$nametype]['file_type'] = '.doc|.docx|.pdf|.rar|.zip|.ppt|.pptx|.xls|.xlsx';

// /* (List) */
// $config['news'][$nametype]['title_main_list'] = "Danh mục cấp 1";
// $config['news'][$nametype]['images_list'] = true;
// $config['news'][$nametype]['show_images_list'] = true;
// $config['news'][$nametype]['slug_list'] = true;
// $config['news'][$nametype]['check_list'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['gallery_list'] = array();
// $config['news'][$nametype]['desc_list'] = true;
// $config['news'][$nametype]['desc_cke_list'] = false;
// $config['news'][$nametype]['content_list'] = false;
// $config['news'][$nametype]['content_cke_list'] = false;
// $config['news'][$nametype]['seo_list'] = true;
// $config['news'][$nametype]['width_list'] = 600;
// $config['news'][$nametype]['height_list'] = 360;
// $config['news'][$nametype]['thumb_list'] = '100x100x1';
// $config['news'][$nametype]['icon_list'] = false;
// $config['news'][$nametype]['width_icon_list'] = 200;
// $config['news'][$nametype]['height_icon_list'] = 130;
// $config['news'][$nametype]['thumb_icon_list'] = '100x65x1';
// $config['news'][$nametype]['img_type_list'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';
/* Kiến thức */
$nametype = "kien-thuc";
$config['news'][$nametype]['title_main'] = "Kiến thức";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("noibat" => "Nổi bật", "hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['copy_image'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Dự án */
$nametype = "du-an";
$config['news'][$nametype]['title_main'] = "Dự án";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("noibat" => "Nổi bật", "hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['copy_image'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Tuyển dụng */
$nametype = "tuyen-dung";
$config['news'][$nametype]['title_main'] = "Tuyển dụng";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['copy_image'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Hệ thống cửa hàng */
$nametype = "chi-nhanh";
$config['news'][$nametype]['title_main'] = "Hệ thống cửa hàng";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['iframe'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

$nametype = "khach-hang";
$config['news'][$nametype]['title_main'] = "Khách hàng";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['subname'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['desc_cke'] = false;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 200;
$config['news'][$nametype]['height'] = 200;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['icon'] = true;
$config['news'][$nametype]['width_icon'] = 380;
$config['news'][$nametype]['height_icon'] = 204;
$config['news'][$nametype]['thumb_icon'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

// $nametype = "doi-ngu";
// $config['news'][$nametype]['title_main'] = "Đội ngũ";
// $config['news'][$nametype]['check'] = array("gioithieu" => "Giới thiệu", "footer" => "Footer", "sanpham" => "Sản phẩm", "hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = false;
// $config['news'][$nametype]['slug'] = false;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['subname'] = true;
// $config['news'][$nametype]['images'] = true;
// $config['news'][$nametype]['show_images'] = true;
// $config['news'][$nametype]['phone'] = true;
// $config['news'][$nametype]['zalo'] = true;
// $config['news'][$nametype]['desc'] = true;
// $config['news'][$nametype]['desc_cke'] = false;
// $config['news'][$nametype]['content'] = false;
// $config['news'][$nametype]['content_cke'] = false;
// $config['news'][$nametype]['seo'] = false;
// $config['news'][$nametype]['schema'] = false;
// $config['news'][$nametype]['width'] = 200;
// $config['news'][$nametype]['height'] = 200;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['icon'] = true;
// $config['news'][$nametype]['width_icon'] = 380;
// $config['news'][$nametype]['height_icon'] = 204;
// $config['news'][$nametype]['thumb_icon'] = '100x100x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Quá trình phát triển */
$nametype = "lich-su-hinh-thanh";
$config['news'][$nametype]['title_main'] = "Lịch sử hình thành";
$config['news'][$nametype]['dropdown'] = false;
$config['news'][$nametype]['list'] = false;
$config['news'][$nametype]['cat'] = false;
$config['news'][$nametype]['item'] = false;
$config['news'][$nametype]['sub'] = false;
$config['news'][$nametype]['tags'] = false;
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['copy_image'] = true;
$config['news'][$nametype]['comment'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['gallery'] = array();
$config['news'][$nametype]['position'] = array();
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['desc_cke'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['thoigian'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 350;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['icon'] = false;
$config['news'][$nametype]['width_icon'] = 30;
$config['news'][$nametype]['height_icon'] = 30;
$config['news'][$nametype]['thumb_icon'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

$nametype = "thong-so";
$config['news'][$nametype]['title_main'] = "Thông số";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = false;
$config['news'][$nametype]['show_images'] = false;
$config['news'][$nametype]['subname'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 100;
$config['news'][$nametype]['height'] = 100;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';



$nametype = "vi-sao";
$config['news'][$nametype]['title_main'] = "Vì sao chọn chúng tôi";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['subname'] = false;
$config['news'][$nametype]['desc'] = false;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['position'] = array();
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 50;
$config['news'][$nametype]['height'] = 50;
$config['news'][$nametype]['thumb'] = '100x100x2';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

$nametype = "cau-hoi";
$config['news'][$nametype]['title_main'] = "Câu hỏi thường gặp";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = false;
$config['news'][$nametype]['show_images'] = false;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 345;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

$nametype = "gia-tri";
$config['news'][$nametype]['title_main'] = "Giá trị cốt lõi";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['subname'] = false;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['position'] = array();
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 100;
$config['news'][$nametype]['height'] = 100;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

$nametype = "tieu-chi";
$config['news'][$nametype]['title_main'] = "Tiêu chí";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 56;
$config['news'][$nametype]['height'] = 56;
$config['news'][$nametype]['thumb'] = '56x56x2';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';


$nametype = "van-hoa";
$config['news'][$nametype]['title_main'] = "Văn hoá doanh nghiệp";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = false;
$config['news'][$nametype]['slug'] = false;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['desc'] = true;
$config['news'][$nametype]['content'] = false;
$config['news'][$nametype]['content_cke'] = false;
$config['news'][$nametype]['seo'] = false;
$config['news'][$nametype]['schema'] = false;
$config['news'][$nametype]['width'] = 100;
$config['news'][$nametype]['height'] = 100;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

// $nametype = "don-hang-ao";
// $config['news'][$nametype]['title_main'] = "Đơn hàng ảo";
// $config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = false;
// $config['news'][$nametype]['slug'] = false;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['link'] = true;
// $config['news'][$nametype]['images'] = true;
// $config['news'][$nametype]['show_images'] = true;
// $config['news'][$nametype]['thoigian'] = true;
// $config['news'][$nametype]['time'] = true;
// $config['news'][$nametype]['subname'] = true;
// $config['news'][$nametype]['content'] = false;
// $config['news'][$nametype]['content_cke'] = false;
// $config['news'][$nametype]['seo'] = false;
// $config['news'][$nametype]['schema'] = false;
// $config['news'][$nametype]['width'] = 100;
// $config['news'][$nametype]['height'] = 100;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

// $nametype = "quy-trinh-thu-mua";
// $config['news'][$nametype]['title_main'] = "Quy trình";
// $config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = false;
// $config['news'][$nametype]['slug'] = false;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['images'] = true;
// $config['news'][$nametype]['show_images'] = true;
// $config['news'][$nametype]['subname'] = false;
// $config['news'][$nametype]['desc'] = true;
// $config['news'][$nametype]['content'] = false;
// $config['news'][$nametype]['content_cke'] = false;
// $config['news'][$nametype]['position'] = array();
// $config['news'][$nametype]['seo'] = false;
// $config['news'][$nametype]['schema'] = false;
// $config['news'][$nametype]['width'] = 540;
// $config['news'][$nametype]['height'] = 360;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';


// $nametype = "thu-mua-xe";
// $config['news'][$nametype]['title_main'] = "Bài viết khác";
// $config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = true;
// $config['news'][$nametype]['slug'] = false;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['images'] = false;
// $config['news'][$nametype]['show_images'] = false;
// $config['news'][$nametype]['desc'] = false;
// $config['news'][$nametype]['content'] = true;
// $config['news'][$nametype]['content_cke'] = true;
// $config['news'][$nametype]['seo'] = false;
// $config['news'][$nametype]['schema'] = false;
// $config['news'][$nametype]['width'] = 500;
// $config['news'][$nametype]['height'] = 333;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Hướng dẫn mua hàng */
// $nametype = "huong-dan";
// $config['news'][$nametype]['title_main'] = "Hướng dẫn";
// $config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
// $config['news'][$nametype]['view'] = true;
// $config['news'][$nametype]['slug'] = true;
// $config['news'][$nametype]['copy'] = true;
// $config['news'][$nametype]['images'] = true;
// $config['news'][$nametype]['show_images'] = true;
// $config['news'][$nametype]['content'] = true;
// $config['news'][$nametype]['content_cke'] = true;
// $config['news'][$nametype]['seo'] = true;
// $config['news'][$nametype]['schema'] = true;
// $config['news'][$nametype]['width'] = 600;
// $config['news'][$nametype]['height'] = 360;
// $config['news'][$nametype]['thumb'] = '100x100x1';
// $config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Chính sách */
$nametype = "chinh-sach";
$config['news'][$nametype]['title_main'] = "Chính sách";
$config['news'][$nametype]['check'] = array("hienthi" => "Hiển thị");
$config['news'][$nametype]['view'] = true;
$config['news'][$nametype]['slug'] = true;
$config['news'][$nametype]['copy'] = true;
$config['news'][$nametype]['images'] = true;
$config['news'][$nametype]['show_images'] = true;
$config['news'][$nametype]['content'] = true;
$config['news'][$nametype]['content_cke'] = true;
$config['news'][$nametype]['seo'] = true;
$config['news'][$nametype]['schema'] = true;
$config['news'][$nametype]['width'] = 600;
$config['news'][$nametype]['height'] = 360;
$config['news'][$nametype]['thumb'] = '100x100x1';
$config['news'][$nametype]['img_type'] = '.jpg|.gif|.png|.jpeg|.gif|.webp|.WEBP|svg';

/* Hình thức thanh toán */
// $nametype = "hinh-thuc-thanh-toan";
// $config['news']['hinh-thuc-thanh-toan']['title_main'] = hinhthucthanhtoan;
// $config['news']['hinh-thuc-thanh-toan']['check'] = array("hienthi" => "Hiển thị");
// $config['news']['hinh-thuc-thanh-toan']['copy'] = true;
// $config['news']['hinh-thuc-thanh-toan']['desc'] = true;
// $config['news']['hinh-thuc-thanh-toan']['desc_cke'] = true;

/* Quản lý mục (Không cấp) */
if (isset($config['news'])) {
    foreach ($config['news'] as $key => $value) {
        if (!isset($value['dropdown']) || (isset($value['dropdown']) && $value['dropdown'] == false)) {
            $config['shownews'] = 1;
            break;
        }
    }
}
